name: 'Minify Assets Files(css/js)'
on:
  push:
    branches:
      - master
    paths:
      - 'dist/**'
      - 'src/**'
  pull_request:
    paths:
      - 'dist/**'
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Auto Minify
        uses: nizarmah/auto-minify@master
        with:
          directory: 'src'
      - name: Auto Minify
        uses: nizarmah/auto-minify@master
        with:
          directory: 'dist'
      - name: Run Makefile
        run: |
          make test
      - name: Commit Minified files
        uses: stefanzweifel/git-auto-commit-action@v3.0.0
        with:
          commit_message: ":arrow_up: Auto Minified JS and CSS files"
          branch: ${{ github.ref }}

